- README.md
- demos/docker-compose/device/docker-compose.yaml
- docs/USER_GUIDE.md
- images/child-device/connector/client.py
- images/child-device/connector/management/metrics.py
- images/debian-systemd/docker-compose.yaml
- justfile
* docs: add user guide
* feat: use custom explicit .env file path
* fix: raise exception if mqtt broker connect fails
* fix: change child device metric series names
Signed-off-by: Reuben Miller <reuben.d.miller@gmail.com>
> Fix-general-improvements

- .github/workflows/test.yaml
- .gitignore
- .vscode/settings.json
- README.md
- demos/docker-compose/device/docker-compose.yaml
- docs/TESTING_WORKFLOW.md
- env.template
- images/child-device/connector/app.py
- images/child-device/connector/client.py
- images/debian-systemd/docker-compose.yaml
- justfile
- tests/children/operations.robot
- tests/children/telemetry.robot
- tests/main/operations.robot
- tests/main/telemetry.robot
- tests/requirements.txt
- tests/resources/common.robot
Add integration to check the features used in the demo container
* Use robot framework to run tests
* Spin up the docker compose image and cleanup any artifacts afterwards
* Only send child device health up status once the child device has been registered
> Add integration tests

- .github/workflows/test.yaml
Prevent duplicate workflow runs when a new PR is created.
> fix(build): remove duplicate workflow PR trigger

- .github/workflows/test.yaml
- images/common/config/tedge.toml
- tests/main/operations.robot
- tests/requirements.txt
Fix some issues with the log file demo:
* use default log and data paths (this was the root cause for the log file retrieval to fail)
* add integration tests to cover log file requests
> Fix-default-log-locations

- README.md
Detail known issue regarding the empty software list on initial startup.
> docs: add empty software list known issue

- README.md
- images/debian-systemd/debian-systemd.dockerfile
- justfile
This allows the script be be called from anywhere in the filesystem.
> feat: add bootstrap.sh to default PATH

- images/child-device/connector/client.py
Improve the child MQTT connector callback logic:
* don't stop the paho network loop if the connection confirmation has not been reached after x seconds, just let paho look after reconnecting
* use callback factory to create the closure to prevent the local variable from being overwritten
> fix(child): refactor mqtt connect and don't stop the loop on unexpected errors

- images/child-device/connector/client.py
Again some more fixes to the python child connection mqtt connection logic:
* only assign the paho mqtt client to the instance after the `.connect` call so that if the mqtt broker url is not reachable, it does not prevent the client from reconnecting.
> fix(child): handle error during initial mqtt connection when broker is not reachable

- images/common/config/tedge-container-plugin.env
Expose additional tedge-container-plugin settings, so it is easier to control aspects of the plugin.
> feat: expose additional tedge-container-plugin settings

- README.md
- docs/USER_GUIDE.md
- images/common/bootstrap.sh
Add a list of known working configurations on setting up for different environments.
> docs: add notes about known working configurations

- images/alpine-s6/alpine-s6.dockerfile
Add community plugins to the alpine-s6 image
* c8y-command-plugin
* tedge-apk-plugin
> feat(alpine-s6): add community plugins

- .github/workflows/test.yaml
- demos/docker-compose/alpine-s6/README.md
- demos/docker-compose/alpine-s6/docker-compose.yaml
- docs/DEVELOPMENT.md
- images/alpine-s6/alpine-s6.dockerfile
- images/alpine-s6/bootstrap.sh
- justfile
- tests/alpine-s6/main/telemetry.robot
Publish alpine-s6 container images (published on a new release)
> build: publish alpine s6 images (both main device and mosquitto image)

- images/common/utils/on_shutdown.sh
- images/common/utils/startup-notifier/startup-notifier
qos 1 prevents message lost as mosquitto will queue the persist the message when qos >= 1
> publish startup and shutdown messages with qos 1

- demos/docker-compose/tedge-containermgmt/README.md
- demos/docker-compose/tedge-containermgmt/docker-compose.yaml
- demos/docker-compose/tedge/README.md
- images/tedge-containermgmt/docker-compose.yaml
Adding instructions for using single container images and how to bootstrap them
> update single container images and instructions

- .github/workflows/test.yaml
- justfile
- tests/tedge/children/operations.robot
- tests/tedge/children/tedge-configuration-plugin-1.toml
- tests/tedge/children/tedge-configuration-plugin-2.toml
- tests/tedge/children/telemetry.robot
- tests/tedge/main/operations.robot
- tests/tedge/main/telemetry.robot
Extend testing to new single process container image.
> test: extend tests to include tedge container image

- .github/workflows/test.yaml
Run tests in parallel to speed up the execution time
> ci: run tests in parallel

- images/common/bootstrap.sh
- images/common/optional-installer.sh
Remove logic which is outdated or no longer required.
> chore: remove old setup and bootstrapping logic

- images/alpine-s6/tedge-configuration-plugin.toml
- images/alpine-s6/tedge-log-plugin.toml
- images/child-device-container/child.dockerfile
- images/child-device-container/config/tedge-configuration-plugin.toml
- images/child-device-systemd/child.dockerfile
- images/child-device-systemd/config/tedge-configuration-plugin.toml
- images/common/config/tedge-configuration-plugin.toml
- images/common/config/tedge-log-plugin.toml
- images/tedge/tedge-configuration-plugin.toml
- tests/alpine-s6/children/tedge-configuration-plugin-1.toml
- tests/alpine-s6/children/tedge-configuration-plugin-2.toml
- tests/tedge/data/tedge-configuration-plugin-1.toml
- tests/tedge/data/tedge-configuration-plugin-2.toml
Include the tedge-log-plugin.toml in the configuration list by default
> feat: add tedge-log-plugin to list of configuration that can be changed

- images/child-device-container/child.dockerfile
- images/child-device-container/entrypoint.sh
- images/child-device-systemd/child.dockerfile
- images/common/utils/set-firmware-version
- images/common/utils/set-startup-info
- images/debian-systemd/debian-systemd.dockerfile
- tests/debian-systemd/children-container/operations.robot
- tests/debian-systemd/children-systemd/operations.robot
Set the c8y_Firmware and c8y_Hardware information on startup to give a better first impression to the user
> feat(systemd): set initial firmware and hardware info on startup

- README.md
Update the child device capability list to include the shell feature.
> docs: add shell capability to child device

- .github/workflows/test.yaml
- images/alpine-s6/alpine-s6.dockerfile
- images/debian-systemd/debian-systemd.dockerfile
- justfile
Run systemd tests both on the latest official release and the latest main branch release.
> tests: run system tests against last official release and from the tedge main branch

- images/child-device-container/entrypoint.sh
- images/common/optional-installer.sh
Fix some minor typos in the project
> lint: fix typos in scripts

- images/common/bootstrap.sh
Added support for Cumulocity Basic Auth (username/password) in the bootstrap script.
Users can now choose between certificate-based or basic authentication during device setup.
> feat: option to bootstrap using Cumulocity basic auth
