- demos/docker-compose/device/docker-compose.yaml
Always pull the container images so that newer images are detected by default.
Signed-off-by: Reuben Miller <reuben.d.miller@gmail.com>
> fix: always pull container images

- demos/docker-compose/device/docker-compose.yaml
- images/debian-systemd/docker-compose.yaml
Support using a custom device type via the `DEVICE_TYPE` environment variable
Signed-off-by: Reuben Miller <reuben.d.miller@gmail.com>
> feat: support custom device type for main device

- images/common/bootstrap.sh
- images/common/config/bootstrap/post.d/10-start-services.sh
- images/common/config/tedge-container-plugin.env
- images/common/optional-installer.sh
- images/debian-systemd/debian-systemd.dockerfile
The `tedge-container-plugin` was causing a few issues by starting too early. This would result in services being registered as child devices by Cumulocity as measurements would be pushed before the service was created by thin-edge.io
* Support post bootstrap script hooks (used to disable the service after the device has been bootstrapped)
* Delay the starting of the tedge-container-monitor service until after bootstrapping
**Note**: There may still be an issue in some instances, however the `tedge-container-plugin` will be adjusted to fix the root cause.
> Fix container plugin integration

- .github/workflows/test.yaml
Remove manual confirmation required when running on main and merge queue.
> ci: use auto deployment when not reviewing PRs

- demos/docker-compose/device/docker-compose.yaml
- env.template
- images/debian-systemd/docker-compose.yaml
Initial support for podman (though no instructions just yet), as support is still experimental.
* Remove usage of `links` as this is is deprecated/legacy compose syntax
* Remove unnecessary`depends_on` for child devices as child containers will dynamically wait for the main device to be ready
* Support customizing the docker socket via an `.env` file when starting the docker compose project (required for podman to work as the docker socket is not located as `/var/run/docker.sock` for podman
> Fix podman compatibility

- images/child-device/connector/app.py
- images/child-device/connector/client.py
- images/child-device/connector/management/metrics.py
- justfile
- tests/main/operations.robot
Fixing handling of the child device MQTT connection which resulted in the child connector not reacting to messages sent via MQTT.
The following improvements were made:
* feat(child): enable paho mqtt client logging by default
* feat(child): subscribe to topics using qos 2
* fix(child): prevent log spamming when checking metrics
* chore(child): format/lint
* feat(child): clean shutdown of client and threads
* fix(child): don't stop mqtt loop on disconnect
* fix(test): increase install timeouts to cater for devices with less CPU resources allocated to it
> fix: resolve child connector MQTT reconnection bug

- images/common/config/bootstrap/post.d/10-start-services.sh
Enable sshd out of the box by enabling/starting the sshd service after bootstrapping.
> feat(ssh): enable sshd service by default during bootstrapping

- images/common/bootstrap.sh
fix(bootstrap): normalize c8y.url before displaying it to prevent invalid url links
> fix(bootstrap): normalize c8y.url before displaying it to prevent invalid url links

- images/common/config/collectd.conf.d/tedge-monitoring.conf
- images/debian-systemd/debian-systemd.dockerfile
- tests/main/telemetry.robot
Add process metrics for individual tedge processes and mosquitto as well as a summation of all tedge components (called "tedge-all") to give an overview of all resources consumed by thin-edge.io.
> feat(telemetry): monitor tedge processes with collectd

- images/common/bootstrap.sh
Fix sed bug where `-E` was forgotten when stripping the `https://` prefix before displaying the device link after bootstrapping
> fix: fix normalization bug before displaying the c8y.url

- images/common/config/bootstrap/post.d/10-start-services.sh
Restart collectd as sometimes it fail with the error:
```
mqtt plugin: mosquitto_connect failed: Cannot assign requested address
```
Seems to be related to: https://github.com/collectd/collectd/issues/3834
> fix: restart collectd service after bootstrapping due to sporadic init issue

- images/common/utils/startup-notifier/startup-notifier.service
Add a more description description to the `startup-notifier` service.
> fix: improve service description for the startup-notifier

- images/child-device/connector/client.py
The following host names / ip addresses will also be replaced with the tedg endpoint:
* localhost
* 127.0.0.1
> fix(connector): escape dots in regex to avoid accidental matches

- images/alpine-s6/mosquitto/mosquitto.dockerfile
Update the mosquitto version used in the alpine linux s6-overlay demo container.
> chore(s6-overlay): update mosquitto to 2.0.17

- images/alpine-s6/alpine-s6.dockerfile
Remove setting which disabled the run lock files as tedge auto detects whether lock files should be created or not via [2190](https://github.com/thin-edge/thin-edge.io/pull/2190).
> chore(alpine-s6): remove tedge run lock files setting as tedge auto detects this now

- demos/docker-compose/alpine-s6/docker-compose.yaml
- docs/ADVANCED.md
- images/alpine-s6/alpine-s6.dockerfile
- images/alpine-s6/bootstrap.sh
- images/alpine-s6/cont-init.d/configure.sh
- images/alpine-s6/docker-compose.yaml
- images/alpine-s6/mosquitto/mosquitto-entrypoint.sh
- images/alpine-s6/mosquitto/mosquitto.dockerfile
- images/alpine-s6/tedge-configuration-plugin.toml
- images/alpine-s6/tedge-log-plugin.toml
- tests/alpine-s6/children/operations.robot
- tests/alpine-s6/children/tedge-configuration-plugin-1.toml
- tests/alpine-s6/children/tedge-configuration-plugin-2.toml
- tests/alpine-s6/children/telemetry.robot
- tests/requirements.txt
Add a child device in the `s6-overlay` example using the same container image but turning some services off.
> extend s6-overlay example with child devices using thin-edge.io components

- demos/docker-compose/alpine-s6/docker-compose.yaml
- images/alpine-s6/alpine-s6.dockerfile
- images/alpine-s6/cont-init.d/configure.sh
- images/alpine-s6/docker-compose.yaml
- tests/alpine-s6/children/operations.robot
Move the tedge-mapper-c8y into an independent container.
There are a few "workarounds" required to make this happen, however thin-edge.io tickets have been created so that when they are resolved, the setup can be simplified even further.
* c8y-firmware-plugin still needs to be run along side the tedge-mapper-c8y as it needs access to the tedge certificate still.
* http.bind.address needs to be manually set on startup. https://github.com/thin-edge/thin-edge.io/issues/2391
* child device needs to be registered manually on startup. https://github.com/thin-edge/thin-edge.io/issues/2389
* tedge-mapper-c8y still needs access to the /var/tedge folder used by the tedge-agent. https://github.com/thin-edge/thin-edge.io/issues/2390
> run tedge-mapper-c8y in an independent container

- tests/alpine-s6/children/operations.robot
Extend system tests for the s6-overlay child device
> test(s6-overlay): add tests for software list and device restart

- demos/docker-compose/alpine-s6/docker-compose.yaml
- docs/ADVANCED.md
- images/alpine-s6/docker-compose.yaml
- images/alpine-s6/mosquitto/mosquitto-entrypoint.sh
- justfile
- tests/alpine-s6/children/operations.robot
- tests/requirements.txt
Cleanup s6-overlay image
* remove unused environment variables
* extend system tests to check installing/removing applications (though user: root is required) - Note: the default user is still tedge and not root in the demo docker compose file
* rename s6 overlay image name to tedge-demo-s6
> Refactoring single process container image demo

- images/debian-systemd/debian-systemd.dockerfile
Update debain base version and mosquitto.
Bookworm has been officially released and using it so that the libc versions match those of the sid repository to enable installing the latest version of mosquitto (>=2.0.18) which is not currently available from the stable or backports of bookworm
Install more recent version of mosquitto >= 2.0.18 from debian sid to avoid mosquitto following bugs:
The mosquitto repo can't be used as it does not included builds for arm64/aarch64 (only amd64 and armhf)
* https://github.com/eclipse/mosquitto/issues/2604 (2.0.11)
* https://github.com/eclipse/mosquitto/issues/2634 (2.0.15)
> feat: update debian base version and mosquitto

- images/alpine-s6/docker-compose.yaml
- justfile
Previously users would have to start the docker compose project using:
```
just IMAGE=alpine-s6 up
just IMAGE=alpine-s6 down
```
Now the `IMAGE` variable can be set in the environment (or `.env` file)
**file: .env**
```
IMAGE=alpine-s6
```
Then you can use the commands without having to set the `IMAGE=` each time.
```
just up
```
> dev: support setting container IMAGE via environment variable

- tests/debian-systemd/main/operations.robot
Enable uninstall software test since the Cumulocity RobotFramework library now supports it.
> test: add system test for uninstalling software

- images/common/optional-installer.sh
Slim down on optional components and improve the build time of the systemd image by using `--no-install-recommends` when installing docker-ce-cli.
> systemd: skip any optional docker packages to reduce size of systemd image

- images/debian-systemd/debian-systemd.dockerfile
- tests/debian-systemd/main/telemetry.robot
Publish inventory data such as hardware and OS information on device startup.
See the new community [tedge-inventory-plugin](https://github.com/thin-edge/tedge-inventory-plugin) for more details
> feat: add inventory-scripts package

- demos/docker-compose/tedge-containermgmt/docker-compose.yaml
- demos/docker-compose/tedge/docker-compose.yaml
- images/tedge-containermgmt/docker-compose.yaml
- images/tedge/docker-compose.yaml
Removing workarounds after updating thin-edge.io since the following tickets have now been merged:
* https://github.com/thin-edge/thin-edge.io/issues/2523
* https://github.com/thin-edge/thin-edge.io/issues/2477
> chore: remove workarounds after related tickets have been merged

- .github/workflows/test.yaml
- docs/TESTING_WORKFLOW.md
Use deadsnakes gha when running on an arm64. This makes it easier and quicker to test the workflow locally using act on arm64 machines.
> ci: support local workflow runs using act on arm64 systems

- .github/workflows/test.yaml
Use a single approval job before running matrix job to avoid having to approve each matrix job
> ci: improve workflow by only having to manual approve PRs once for each run

- .github/workflows/test.yaml
- images/tedge-containermgmt/Dockerfile
- images/tedge/Dockerfile
- justfile
Avoid rebuilding the project when starting containers used in the tests (as the containers are pre-built)
> ci: skip building the image when calling up

- demos/docker-compose/tedge-containermgmt/docker-compose.yaml
Use a fixed network name called "tedge" to allow other deployed containers to connect to the same network
> feat: add fixed network name to container management example

- demos/docker-compose/tedge-containermgmt/README.md
- demos/docker-compose/tedge-containermgmt/docker-compose.yaml
- demos/docker-compose/tedge/README.md
- demos/docker-compose/tedge/docker-compose.yaml
- images/tedge-containermgmt/docker-compose.yaml
- images/tedge/docker-compose.yaml
Instead all of the bootstrapping settings will be injected during the runtime bootstrapping commands. This reduces dependencies between starting the docker compose and running the bootstrapping.
> remove reliance on bootstrap environment variables

- justfile
Add a release task to ensure consistent naming of releases.
**Example**
```sh
just release
```
> dev: add a release task

- images/debian-systemd/debian-systemd.dockerfile
The community repo is already configured by the thin-edge.io install.sh script.
> refactor: remove manual community repo setup

- .github/workflows/publish.yaml
- .github/workflows/test.yaml
switch the action to install just in the workflows to avoid the node16.x deprecation notices which are present on the previously used action.
> ci: use taiki-e/install-action@just to install just

- images/common/config/tedge.toml
- tests/debian-systemd/main/operations.robot
thin-edge.io 1.1.0 supports a new software management package exclusion filter to ignore uninteresting packages.
Previously an "inclusion" filter was being used (via. apt.name), however this resulted in unexpected behaviour for users wanting to install new packages which didn't match the filter (see [#79](https://github.com/thin-edge/tedge-demo-container/issues/79)).
> feat(software): use software package exclusion pattern to ignore uninteresting packages

- images/debian-systemd/debian-systemd.dockerfile
Install mosquitto from bookworm-backports over sid to avoid unexpected changes to core packages (e.g. systemd, libc etc.).
> fix: install mosquitto from bookworm-backports

- images/debian-systemd/debian-systemd.dockerfile
- images/debian-systemd/docker-compose.yaml
Switch to use `systemd-tmpfiles-setup` service over the tmpfs mounts.
> feat: use systemd-tmpfiles-setup over docker tmpfs

- images/alpine-s6/tedge-log-plugin.toml
- images/common/config/tedge-log-plugin.toml
- images/tedge-containermgmt/tedge-log-plugin.toml
- images/tedge/tedge-log-plugin.toml
- tests/tedge-containermgmt/telemetry-main.robot
The software-managment log file pattern changed in thin-edge.io 1.3.0 which was then causing the system tests to fail.
> chore: update software-management file pattern to align with thin-edge.io 1.3.0

- images/common/bootstrap.sh
- images/common/config/sshd_config
- images/common/optional-installer.sh
- images/debian-systemd/debian-systemd.dockerfile
- tests/debian-systemd/main/system.robot
To resolve https://github.com/thin-edge/tedge-demo-container/issues/83, the following changes were made to enable ssh out of the box (again):
* Create the `iotadmin` user at build time rather than during the bootstrap.sh script (just in case if people are manually bootstrapping the device or using [c8y-tedge](https://github.com/thin-edge/c8y-tedge)).
* Include sshd config which allows ssh users to login with a password (though ssh will only listen on the loopback address, 127.0.0.1)
> fix: enable ssh access out of the box

- demos/docker-compose/device/docker-compose.yaml
- demos/docker-compose/tedge-containermgmt/docker-compose.yaml
- demos/docker-compose/tedge/docker-compose.yaml
- images/alpine-s6/docker-compose.yaml
- images/debian-systemd/docker-compose.yaml
- images/tedge-containermgmt/docker-compose.yaml
- images/tedge/docker-compose.yaml
- tests/tedge-containermgmt/data/docker-compose.nginx.yaml
Remove the usage of the deprecated docker compose version field, to address these warnings:
```
WARN[0000] example/docker-compose.yaml: `version` is obsolete
```
> chore: remove deprecated docker compose version field

- images/common/config/tedge.toml
Useful when applying device profiles from the cloud where the softwareType can be left out. Setting the default type to `apt` is a sensible default for the systemd container as it is debian based.
> feat: set default software type to apt

- images/common/config/tedge-configuration-plugin.toml
Allow management of the tedge-log-plugin out of the box by including it in the default tedge-configuration-plugin.toml configuration.
> feat: add tedge-log-plugin to files which can be managed by tedge-configuration-plugin

- .github/workflows/test.yaml
This change allows the just file task to be extended to add additional test log files collected when shutting down the containers (but the collection of the logs files will be implemented in a follow up PR)
> ci: stop test containers before uploading report

- images/child-device/requirements.txt
Remove a python requirements file which is no longer used after the python agent code was moved to https://github.com/thin-edge/python-tedge-agent
> chore: remove unused python requirements file

- .gitignore
- justfile
- scripts/collect-logs.sh
Automatically collect container log files and workflows before destroying the container setup to assist debugging system test failures.
> ci: collect container log files before destroying it to assist debugging failures

- images/child-device-container/child.dockerfile
- images/child-device-container/entrypoint.sh
- images/child-device-systemd/child.dockerfile
- images/common/config/sudoers.d/step-ca
- images/common/utils/configure-device/runner.sh
- images/common/utils/configure-device/scripts.d/90_start-agent
- images/common/utils/enroll/enroll.sh
- images/common/utils/init-pki/init-pki.sh
- images/debian-systemd/debian-systemd.dockerfile
- images/debian-systemd/docker-compose.yaml
Configure mtls for secure communication between local components and clients.
The demo uses a community project, https://github.com/thin-edge/tedge-pki-smallstep, which uses [step-ca](https://github.com/smallstep/certificates) by [Smallstep](https://smallstep.com/certificates/index.html).
The PKI feature can be enabled or disabled by setting the following environment variable:
```sh
FEATURES=pki
```
Or
```
FEATURES=
```
The `FEATURES` variable will be used in the future for other optional features, and accepts a csv string, e.g. `FEATURES=feature1,feature2` etc.
> feat(debian-systemd): use mtls for all thin-edge.io components by using smallstep as local pki

- tests/tedge-containermgmt/telemetry-main.robot
Re-enable check after the root cause has been fixed.
> test: re-enable tedge-container-monitor service status check

- images/child-device-systemd/child.dockerfile
- images/common/config/tedge.toml
Update to thin-edge.io 1.3.1 and remove workaround which are no longer required
> feat: update to thin-edge.io 1.3.1

- images/alpine-s6/docker-compose.yaml
The workarounds are no longer solved as the linked ticket has been resolved.
> chore: remove file transfer service workarounds

- justfile
Fix the child container publishing tasks which broke when changing to a tedge-agent based images (due to a restructuring of the images)
> ci: fix publishing tasks

- images/child-device-systemd/child.dockerfile
Allow tedge-agent to pull in the recommended packages to ensure it installs sensible packages like tedge-apt-plugin
> fix(child-systemd): install tedge-agent with recommended packages

- images/child-device-systemd/child.dockerfile
- images/debian-systemd/debian-systemd.dockerfile
Minor improvements to provide a more standard environment:
* Change default working directory to `/root` for systemd based images to allow users logging in via docker to be in the user's home directory
* Remove the optional-installer.sh script which is not needed in the final image
> feat(systemd): change default workdir and cleanup installation files

- images/common/utils/set-startup-info
- tests/debian-systemd/children-systemd/operations.robot
- tests/debian-systemd/main/operations.robot
Fix a bug where the firmware information was not being published as a retained MQTT message which resulted in the message being missed if the mapper was not yet started.
Adding system tests to cover this functionality.
> fix(systemd): publish firmware information with retain flag

- images/child-device-container/child.dockerfile
Add a default tedge-log-plugin with more log files configured to better show-case the functionality
> feat(systemd): add default tedge-log-plugin file to child device container

- .github/workflows/test.yaml
Try to reduce irregularities during system tests by building first and then starting everything up, otherwise the containers can startup at wildly different times.
> ci: build the entire compose project before starting it to avoid race conditions

- images/child-device-container/entrypoint.sh
- tests/debian-systemd/children-container/operations.robot
Adding missing system test for the child-container image
> test: add missing firmware init information test

- .github/workflows/test.yaml
- images/alpine-s6/bootstrap.sh
- images/alpine-s6/mosquitto/mosquitto-entrypoint.sh
- images/common/bootstrap.sh
Improve the workflow and surrounding actions like bootstrapping:
* Stop running test twice for the same commit (merge_group and when the merge_group is committed to main)
* Stop trying to build the compose image after using the prepare
* Refactor bootstrap logic to use tedge to prompt for missing information
> ci: streamline test workflow

- images/common/config/bootstrap/post.d/10-start-services.sh
Removing workarounds which are no longer required
> refactor: remove workaround which started two started ssh and tedge-container-monitor

- images/child-device-container/child.dockerfile
- images/child-device-systemd/child.dockerfile
- images/common/utils/set-agent-info
- tests/debian-systemd/children-container/telemetry.robot
- tests/debian-systemd/children-systemd/telemetry.robot
Support publishing agent information including the version to make it easier to debug/track
> feat(systemd): publish agent information on child devices

- images/child-device-container/config/tedge-log-plugin.toml
- images/child-device-systemd/config/tedge-log-plugin.toml
- images/common/config/tedge-log-plugin.toml
- images/common/utils/workflows/firmware_update.toml
- tests/debian-systemd/children-container/operations.robot
- tests/debian-systemd/children-systemd/operations.robot
- tests/debian-systemd/main/operations.robot
- tests/debian-systemd/tedge-configuration-plugin.toml
- tests/requirements.txt
Manually publish the new firmware name/version because when installing firmware via a device profile, the name/version isn't updated.
> fix: device profile firmware interaction

- README.md
- demos/docker-compose/device/docker-compose.yaml
Update the docker compose used by `c8y tedge demo start` to use the latest demo setup with extended features:
* Use tedge-agent as child device (both in systemd and single process container configurations)
* Enable device profile support
* Add firmware update workflow
> release(systemd): update default demo docker compose file to use new systemd tedge-agent setup

- images/debian-systemd/debian-systemd.dockerfile
Use mosquitto 2.0.11 (the default for debian bookworm) and avoid using mosquitto 2.0.18 due to a session persistence bug when using `per_listener_settings true`.
See https://github.com/thin-edge/thin-edge.io/issues/3185 for more details
> fix: use mosquitto 2.0.11 by default

- images/common/utils/startup-notifier/startup-notifier
- tests/debian-systemd/main/operations.robot
Publish the MQTT startup message using QoS 2 to prevent sending duplicate events to the cloud.
> fix: use qos 2 to publish startup message

- images/common/optional-installer.sh
Install podman and podman-compose in the demo container
> feat: support container management in demo

- images/common/config/mosquitto-conf/tedge-networkcontainer.conf
- images/common/optional-installer.sh
- images/debian-systemd/debian-systemd.dockerfile
Add an additional mosquitto listener on port 1884 which can be used by containers to read and publish data.
> feat: add mosquitto listener for container network

- images/debian-systemd/debian-systemd.dockerfile
Support deploying nodered flow using [tedge-nodered-plugin-ng](https://github.com/thin-edge/tedge-nodered-plugin/tree/next) which can manage both node-red projects or nodered-flows
> feat: add tedge-nodered-plugin-ng

- images/alpine-s6/alpine-s6.dockerfile
- images/common/config/tedge-configuration-plugin.toml
- images/common/utils/set-startup-info
- images/debian-systemd/debian-systemd.dockerfile
- images/tedge-containermgmt/Dockerfile
- images/tedge/Dockerfile
- tests/alpine-s6/children/operations.robot
- tests/tedge/operations.robot
Use new generic tedge-command-plugin which uses a new thin-edge.io 1.4.0 feature which allows custom operation handlers to use thin-edge.io workflows.
> feat: use new tedge-command-plugin

- images/child-device-container/child.dockerfile
- images/child-device-systemd/child.dockerfile
- tests/debian-systemd/children-container/operations.robot
- tests/debian-systemd/children-systemd/operations.robot
Install tedge-command-plugin on the child device images to show-off the new workflow based operation handler.
> feat: add tedge-command-plugin to child device images

- images/common/config/collectd.conf
Previously collectd was also monitoring files which are mounted within the container, e.g. `/etc/resolv.conf` which was causing an issue in Cumulocity as the measurement name had a "." in it.
Below shows an example of the Cumulocity error presented to the user:
> fix(collectd): only monitor disk usage of rootfs and overlay partitions

- images/debian-systemd/debian-systemd.dockerfile
Add tedge-monit-setup package which installs monit along with some thin-edge.io releated monitoring rules.
monit includes a http service endpoint which can then be used to demonstrate the [cumulocity-remote-access-cloud-http-proxy](https://github.com/Cumulocity-IoT/cumulocity-remote-access-cloud-http-proxy) functionality.
Resolves https://github.com/thin-edge/tedge-demo-container/issues/129
> feat: add tedge-monit-setup package to demo

- images/common/config/mosquitto.conf
Prevent messages from being dropped due to the max inflight message limit of mosquitto being limit being exceeded.
> fix: increase mosquitto default inflight message limit

- .github/workflows/test.yaml
ubuntu-20.04 runners have been deprecated, so replace the usage with supported runners.
> ci: remove usage of deprecated ubuntu-20.04 runners

- README.md
- images/common/optional-installer.sh
- images/debian-systemd/debian-systemd.dockerfile
- justfile
Install and configure the following shells so that `tedge` tab completion works out of the box for the root and `iotadmin` user.
* bash
* zsh
* fish
> feat: enable tedge tab completions

- README.md
Add instructions for using go-c8y-cli and c8y-tedge to start a demo container as this should be the preferred way rather than manually checking out the project.
> docs: add instructions for using go-c8y-cli and c8y-tedge to launch a demo container
